name: FITNESS_LINTING

on: 
    pull_request: 
        branches: ["develop"]

jobs:
    client_ci:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: client
        steps:
            - uses: actions/checkout@master
            - name: install dependencies
              run: npm i
            - name: run building 
              run: npm run build