name: FITNESS-DEPLOY

on:
    push:
        branches: ["master"]

env:
    LOGIN: ${{secrets.DOCKER_LOGIN}}
    PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    SERVER_NAME: ${{secrets.DOCKER_SERVER_NAME}}
    SSH_USERNAME: ${{secrets.SSH_USERNAME}}
    SSH_HOST: ${{secrets.SSH_HOST}}
    SSH_PASSWORD: ${{secrets.SSH_PASSWORD}}
    SSH_SERVER_SCRIPT: ${{secrets.SSH_SERVER_SCRIPT}}
    SSH_CLIENT_DIST: ${{secrets.SSH_CLIENT_DIST}}

jobs:
    server_build:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: server
      steps:
        - uses: actions/checkout@master
        - name: login to docker
          run: |
            docker login -u ${{env.LOGIN}} -p ${{env.PASSWORD}}
        - name: build image
          run: docker build -t ${{env.LOGIN}}/${{env.SERVER_NAME}}:deploy -f Dockerfile .
        - name: push build
          run: docker push ${{env.LOGIN}}/${{env.SERVER_NAME}}:deploy

    client_build_deploy:
      runs-on: ubuntu-latest
      needs: server_build
      defaults:
        run:
          working-directory: client
      steps:
        - uses: actions/checkout@master
        - name: install dependencies
          run: npm i
        - name: build
          run: npm run build

        - uses: actions/checkout@master
        - name: ssh connection
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{env.SSH_HOST}}
            username: ${{env.SSH_USERNAME}}
            password: ${{env.SSH_PASSWORD}}
            script: bash ${{env.SSH_SERVER_SCRIPT}}

        - name: uppdate file on server
          uses: appleboy/scp-action@v0.1.7
          with:
            host: ${{env.SSH_HOST}}
            username: ${{env.SSH_USERNAME}}
            password: ${{env.SSH_PASSWORD}}
            source: "client/dist/*"
            target: ${{env.SSH_CLIENT_DIST}}